CREATE DATABASE HEART_DB;

CREATE OR REPLACE TABLE HEART_DB.PUBLIC.FINAL_DATA (
	AGE VARCHAR(50),
	SEX VARCHAR(50),
	CP VARCHAR(50),
	TRESTBPS VARCHAR(50),
	CHOL VARCHAR(50),
	FBS VARCHAR(50),
	RESTECG VARCHAR(50),
	THALACH VARCHAR(50),
	EXANG VARCHAR(50),
	OLDPEAK VARCHAR(50),
	THAL VARCHAR(50),
	LOGISTICREGRESSION VARCHAR(50),
	GAUSSIANNB VARCHAR(50),
	KNEIGHBORSCLASSIFIER VARCHAR(50),
	DECISIONTREECLASSIFIER VARCHAR(50),
	RANDOMFORESTCLASSIFIER VARCHAR(50),
	LOGISTICREGRESSION_ACCURACY VARCHAR(50),
	GAUSSIANNB_ACCURACY VARCHAR(50),
	KNEIGHBORSCLASSIFIER_ACCURACY VARCHAR(50),
	DECISIONTREECLASSIFIER_ACCURACY VARCHAR(50),
	RANDOMFORESTCLASSIFIER_ACCURACY VARCHAR(50),
	TIME_STAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE HEART_DB.PUBLIC.INPUT_DATA (
	AGE VARCHAR(100),
	SEX VARCHAR(100),
	CP VARCHAR(100),
	TRESTBPS VARCHAR(100),
	CHOL VARCHAR(100),
	FBS VARCHAR(100),
	RESTECG VARCHAR(100),
	THALACH VARCHAR(100),
	EXANG VARCHAR(100),
	OLDPEAK VARCHAR(100),
	SLOPE VARCHAR(100),
	CA VARCHAR(100),
	THAL VARCHAR(100)
);


CREATE OR REPLACE TABLE HEART_DB.PUBLIC.PREDICTED_DATA (
	AGE NUMBER(38,0),
	SEX NUMBER(38,0),
	CP NUMBER(38,0),
	TRESTBPS NUMBER(38,0),
	CHOL NUMBER(38,0),
	FBS NUMBER(38,0),
	RESTECG NUMBER(38,0),
	THALACH NUMBER(38,0),
	EXANG NUMBER(38,0),
	OLDPEAK NUMBER(38,0),
	SLOPE NUMBER(38,0),
	CA NUMBER(38,0),
	THAL NUMBER(38,0),
	ORG_RESULT NUMBER(38,0)
);

CREATE OR REPLACE TABLE HEART_DB.PUBLIC.FEATURE_IMPORTANCE (
	FEATURE VARCHAR(100),
	IMPORTANCE FLOAT
);